In [64]:
import pandas as pd
data_path = 'Archive/national parks.csv'
df = pd.read_csv(data_path)
df

                               name,location,long&lat
0        Acadia National Park,Maine,44°21′N, 68°13′W﻿
1   American Samoa National Park,American Samoa Te...
2   Arches National Park,Utah,38°43′41″N, 109°32′2...
3   Badlands National Park,South Dakota,43°45′N, 1...
4   Big Bend National Park,Texas,29°15′0″N, 103°15...
5   Biscayne National Park,Florida,25°28′10″N, 80°...
6   Black Canyon of the Gunnison National Park,Col...
7   Bryce Canyon National Park,Utah,37°35′N, 112°1...
8   Canyonlands National Park,Utah,38°10′01″N, 109...
9   Capitol Reef National Park,Utah,38°12′N, 111°10′W
10  Carlsbad Caverns National Park,New Mexico,32°1...
11  Congaree National Park,South Carolina,33.7919°...
12  Crater Lake National Park,Oregon,42°54′43″N, 1...
13  Cuyahoga Valley National Park,Ohio,41.2808° N,...
14  Death Valley National Park,California and Neva...
15  Denali National Park,Alaska,63.2828° N, 150.78...
16  Dry Tortugas National Park,Florida,24.6285° N,...
17  Everglades National Park,Florida,25.2866° N, 8...
18  Gates of the Arctic National Park,Alaska,67°47...
19  Gateway Arch National Park,Missouri,38.6249° N...
20  Glacier National Park,Montana,48.7596° N, 113....
21  Glacier Bay National Park,Alaska,58.6658° N, 1...
22  Grand Canyon National Park,Arizona,36.2679° N,...
23  Grand Teton National Park,Wyoming,43.7904° N, ...
24  Great Basin National Park,Nevada,38.9300° N, 1...
25  Great Sand Dunes National Park,Colorado,37.765...
26  Great Smoky Mountains National Park,North Caro...
27  Guadalupe Mountains National Park,Texas,31.923...
28  Haleakala National Park,Hawaii,20.7204° N, 156...
29  Hawaii Volcanoes National Park,Hawaii,19.4964°...
30  Hot Springs National Park,Arkansas,34.5269° N,...
31  Indiana Dunes National Park,Indiana,41.6533° N...
32  Isle Royale National Park,Michigan,47.9959° N,...
33  Joshua Tree National Park,California,33.8734° ...
34  Katmai National Park,Alaska,58.5862° N, 154.96...
35  Kenai Fjords National Park,Alaska,59.8487° N, ...
36  Kings Canyon National Park,California,36.8879°...
37  Kobuk Valley National Park,Alaska,67.3575° N, ...
38  Lake Clark National Park,Alaska,60.6242° N, 15...
39  Lassen Volcanic Park,California,40.4977° N, 12...
40  Mammoth Cave Park,Kentucky,37.1815° N, 86.1505° W
41  Mesa Verde National Park,Colorado,37.2309° N, ...
42  Mount Rainier National Park,Washington,46.8800...
43  North Cascades National Park,Washington,48.771...
44  Olympic National Park,Washington,47.8021° N, 1...
45  Petrified Forest National Park,Arizona,34.9583...
46  Pinnacles National Park,California,36.4906° N,...
47  Redwood National Park,California,41.4017° N, 1...
48  Rocky Mountain National Park,Colorado,40.3428°...
49  Saguaro National Park,Arizona,32.1831° N, 110....
50  Sequoia National Park,California,36.4864° N, 1...
51  Shenandoah National Park,Virginia,38.4755° N, ...
52  Theodore Roosevelt National Park,North Dakota,...
53  Virgin Islands National Park,U.S. Virgin Islan...
54  Voyageurs National Park,Minnesota,48.4711° N, ...
55  Wind Cave National Park,South Dakota,43.5724° ...
56  Wrangell-St. Elias National Park,Alaska,60.923...
57  Yellowstone National Park,Wyoming,44.4280° N, ...
58  Yosemite National Park,California,37.8651° N, ...
59    Zion National Park,Utah,37.2982° N, 113.0263° W

In [65]:


# Split the 'name,location,long&lat' column into 'name', 'location', 'latitude', and 'longitude'
df[['name', 'location', 'lat', 'long']] = df['name,location,long&lat'].str.split(',', expand=True)
# Remove the original 'name,location,long&lat' column
df.drop('name,location,long&lat', axis=1, inplace=True)

# Display the updated DataFrame
print(df)

                                          name                      location  \
0                         Acadia National Park                         Maine
1                 American Samoa National Park      American Samoa Territory
2                         Arches National Park                          Utah
3                       Badlands National Park                  South Dakota
4                       Big Bend National Park                         Texas
5                       Biscayne National Park                       Florida
6   Black Canyon of the Gunnison National Park                      Colorado
7                   Bryce Canyon National Park                          Utah
8                    Canyonlands National Park                          Utah
9                   Capitol Reef National Park                          Utah
10              Carlsbad Caverns National Park                    New Mexico
11                      Congaree National Park                South Carolina
12                   Crater Lake National Park                        Oregon
13               Cuyahoga Valley National Park                          Ohio
14                  Death Valley National Park         California and Nevada
15                        Denali National Park                        Alaska
16                  Dry Tortugas National Park                       Florida
17                    Everglades National Park                       Florida
18           Gates of the Arctic National Park                        Alaska
19                  Gateway Arch National Park                      Missouri
20                       Glacier National Park                       Montana
21                   Glacier Bay National Park                        Alaska
22                  Grand Canyon National Park                       Arizona
23                   Grand Teton National Park                       Wyoming
24                   Great Basin National Park                        Nevada
25              Great Sand Dunes National Park                      Colorado
26         Great Smoky Mountains National Park  North Carolina and Tennessee
27           Guadalupe Mountains National Park                         Texas
28                     Haleakala National Park                        Hawaii
29              Hawaii Volcanoes National Park                        Hawaii
30                   Hot Springs National Park                      Arkansas
31                 Indiana Dunes National Park                       Indiana
32                   Isle Royale National Park                      Michigan
33                   Joshua Tree National Park                    California
34                        Katmai National Park                        Alaska
35                  Kenai Fjords National Park                        Alaska
36                  Kings Canyon National Park                    California
37                  Kobuk Valley National Park                        Alaska
38                    Lake Clark National Park                        Alaska
39                        Lassen Volcanic Park                    California
40                           Mammoth Cave Park                      Kentucky
41                    Mesa Verde National Park                      Colorado
42                 Mount Rainier National Park                    Washington
43                North Cascades National Park                    Washington
44                       Olympic National Park                    Washington
45              Petrified Forest National Park                       Arizona
46                     Pinnacles National Park                    California
47                       Redwood National Park                    California
48                Rocky Mountain National Park                      Colorado
49                       Saguaro National Park                       Arizona
50                       Sequoia National Park                    California
51                    Shenandoah National Park                      Virginia
52            Theodore Roosevelt National Park                  North Dakota
53                Virgin Islands National Park           U.S. Virgin Islands
54                     Voyageurs National Park                     Minnesota
55                     Wind Cave National Park                  South Dakota
56            Wrangell-St. Elias National Park                        Alaska
57                   Yellowstone National Park                       Wyoming
58                      Yosemite National Park                    California
59                          Zion National Park                          Utah

           lat            long
0      44°21′N        68°13′W﻿
1   14°15′30″S    170°41′00″W﻿
2   38°43′41″N    109°32′24″W﻿
3      43°45′N      102°30′W﻿
4    29°15′0″N      103°15′0″W
5   25°28′10″N    80°11′10″W﻿
6   38°34′45″N   107°43′39″W﻿
7      37°35′N       112°11′W﻿
8   38°10′01″N    109°45′35″W﻿
9      38°12′N        111°10′W
10  32°10′31″N     104°26′38″W
11  33.7919° N      80.7490° W
12  42°54′43″N    122°08′53″W﻿
13  41.2808° N      81.5678° W
14  36.5054° N     117.0794° W
15  63.2828° N     150.7894° W
16  24.6285° N      82.8732° W
17  25.2866° N      80.8987° W
18     67°47′N       153°18′W﻿
19  38.6249° N      90.1859° W
20  48.7596° N     113.7870° W
21  58.6658° N     136.9002° W
22  36.2679° N     112.3535° W
23  43.7904° N     110.6818° W
24  38.9300° N     114.2634° W
25  37.7658° N     105.6236° W
26  35.6131° N      83.5532° W
27  31.9233° N     104.8663° W
28  20.7204° N     156.1552° W
29  19.4964° N     155.4662° W
30  34.5269° N      93.0691° W
31  41.6533° N      87.0524° W
32  47.9959° N      88.9093° W
33  33.8734° N     115.9010° W
34  58.5862° N     154.9698° W
35  59.8487° N     150.1879° W
36  36.8879° N     118.5551° W
37  67.3575° N     159.2137° W
38  60.6242° N     153.3058° W
39  40.4977° N     121.4207° W
40  37.1815° N      86.1505° W
41  37.2309° N     108.4618° W
42  46.8800° N     121.7269° W
43  48.7718° N     121.2985° W
44  47.8021° N     123.6044° W
45  34.9583° N     109.7594° W
46  36.4906° N     121.1825° W
47  41.4017° N     124.0417° W
48  40.3428° N     105.6836° W
49  32.1831° N     110.6127° W
50  36.4864° N     118.5658° W
51  38.4755° N      78.4535° W
52  46.9790° N     103.5387° W
53  18.3435° N      64.7501° W
54  48.4711° N      92.8458° W
55  43.5724° N     103.4416° W
56  60.9234° N     142.7339° W
57  44.4280° N     110.5885° W
58  37.8651° N     119.5383° W
59  37.2982° N     113.0263° W

In [69]:
# Function to convert coordinates to decimal degrees
def convert_to_decimal(coord):
    parts = coord.split('°')
    degrees = float(parts[0])
    if len(parts) > 1:
        minutes = parts[1].replace('′', '')
        if '″' in minutes:
            minutes, seconds = minutes.split('″')
        else:
            seconds = '0'
        # Ensure only numeric parts are used for conversion
        minutes_numeric = ''.join(filter(str.isdigit, minutes))
        seconds_numeric = ''.join(filter(str.isdigit, seconds))
        if minutes_numeric and seconds_numeric:  # Check if not empty
            decimal_degrees = degrees + float(minutes_numeric) / 60 + float(seconds_numeric) / 3600
        else:
            decimal_degrees = degrees
    else:
        decimal_degrees = degrees
    if 'S' in coord or 'W' in coord:
        decimal_degrees = -decimal_degrees
    return decimal_degrees

# Apply the conversion function to the DataFrame
df['lat_decimal'] = df['lat'].apply(convert_to_decimal)
df['long_decimal'] = df['long'].apply(convert_to_decimal)

# Display the DataFrame with decimal degrees
print(df)

                                          name                      location  \
0                         Acadia National Park                         Maine
1                 American Samoa National Park      American Samoa Territory
2                         Arches National Park                          Utah
3                       Badlands National Park                  South Dakota
4                       Big Bend National Park                         Texas
5                       Biscayne National Park                       Florida
6   Black Canyon of the Gunnison National Park                      Colorado
7                   Bryce Canyon National Park                          Utah
8                    Canyonlands National Park                          Utah
9                   Capitol Reef National Park                          Utah
10              Carlsbad Caverns National Park                    New Mexico
11                      Congaree National Park                South Carolina
12                   Crater Lake National Park                        Oregon
13               Cuyahoga Valley National Park                          Ohio
14                  Death Valley National Park         California and Nevada
15                        Denali National Park                        Alaska
16                  Dry Tortugas National Park                       Florida
17                    Everglades National Park                       Florida
18           Gates of the Arctic National Park                        Alaska
19                  Gateway Arch National Park                      Missouri
20                       Glacier National Park                       Montana
21                   Glacier Bay National Park                        Alaska
22                  Grand Canyon National Park                       Arizona
23                   Grand Teton National Park                       Wyoming
24                   Great Basin National Park                        Nevada
25              Great Sand Dunes National Park                      Colorado
26         Great Smoky Mountains National Park  North Carolina and Tennessee
27           Guadalupe Mountains National Park                         Texas
28                     Haleakala National Park                        Hawaii
29              Hawaii Volcanoes National Park                        Hawaii
30                   Hot Springs National Park                      Arkansas
31                 Indiana Dunes National Park                       Indiana
32                   Isle Royale National Park                      Michigan
33                   Joshua Tree National Park                    California
34                        Katmai National Park                        Alaska
35                  Kenai Fjords National Park                        Alaska
36                  Kings Canyon National Park                    California
37                  Kobuk Valley National Park                        Alaska
38                    Lake Clark National Park                        Alaska
39                        Lassen Volcanic Park                    California
40                           Mammoth Cave Park                      Kentucky
41                    Mesa Verde National Park                      Colorado
42                 Mount Rainier National Park                    Washington
43                North Cascades National Park                    Washington
44                       Olympic National Park                    Washington
45              Petrified Forest National Park                       Arizona
46                     Pinnacles National Park                    California
47                       Redwood National Park                    California
48                Rocky Mountain National Park                      Colorado
49                       Saguaro National Park                       Arizona
50                       Sequoia National Park                    California
51                    Shenandoah National Park                      Virginia
52            Theodore Roosevelt National Park                  North Dakota
53                Virgin Islands National Park           U.S. Virgin Islands
54                     Voyageurs National Park                     Minnesota
55                     Wind Cave National Park                  South Dakota
56            Wrangell-St. Elias National Park                        Alaska
57                   Yellowstone National Park                       Wyoming
58                      Yosemite National Park                    California
59                          Zion National Park                          Utah

           lat            long  lat_decimal  long_decimal
0      44°21′N        68°13′W﻿    44.350000    -68.216667
1   14°15′30″S    170°41′00″W﻿   -14.000000   -170.000000
2   38°43′41″N    109°32′24″W﻿    38.000000   -109.000000
3      43°45′N      102°30′W﻿     43.750000   -102.500000
4    29°15′0″N      103°15′0″W    29.000000   -103.000000
5   25°28′10″N    80°11′10″W﻿     25.000000    -80.000000
6   38°34′45″N   107°43′39″W﻿     38.000000   -107.000000
7      37°35′N       112°11′W﻿    37.583333   -112.183333
8   38°10′01″N    109°45′35″W﻿    38.000000   -109.000000
9      38°12′N        111°10′W    38.200000   -111.166667
10  32°10′31″N     104°26′38″W    32.000000   -104.000000
11  33.7919° N      80.7490° W    33.791900    -80.749000
12  42°54′43″N    122°08′53″W﻿    42.000000   -122.000000
13  41.2808° N      81.5678° W    41.280800    -81.567800
14  36.5054° N     117.0794° W    36.505400   -117.079400
15  63.2828° N     150.7894° W    63.282800   -150.789400
16  24.6285° N      82.8732° W    24.628500    -82.873200
17  25.2866° N      80.8987° W    25.286600    -80.898700
18     67°47′N       153°18′W﻿    67.783333   -153.300000
19  38.6249° N      90.1859° W    38.624900    -90.185900
20  48.7596° N     113.7870° W    48.759600   -113.787000
21  58.6658° N     136.9002° W    58.665800   -136.900200
22  36.2679° N     112.3535° W    36.267900   -112.353500
23  43.7904° N     110.6818° W    43.790400   -110.681800
24  38.9300° N     114.2634° W    38.930000   -114.263400
25  37.7658° N     105.6236° W    37.765800   -105.623600
26  35.6131° N      83.5532° W    35.613100    -83.553200
27  31.9233° N     104.8663° W    31.923300   -104.866300
28  20.7204° N     156.1552° W    20.720400   -156.155200
29  19.4964° N     155.4662° W    19.496400   -155.466200
30  34.5269° N      93.0691° W    34.526900    -93.069100
31  41.6533° N      87.0524° W    41.653300    -87.052400
32  47.9959° N      88.9093° W    47.995900    -88.909300
33  33.8734° N     115.9010° W    33.873400   -115.901000
34  58.5862° N     154.9698° W    58.586200   -154.969800
35  59.8487° N     150.1879° W    59.848700   -150.187900
36  36.8879° N     118.5551° W    36.887900   -118.555100
37  67.3575° N     159.2137° W    67.357500   -159.213700
38  60.6242° N     153.3058° W    60.624200   -153.305800
39  40.4977° N     121.4207° W    40.497700   -121.420700
40  37.1815° N      86.1505° W    37.181500    -86.150500
41  37.2309° N     108.4618° W    37.230900   -108.461800
42  46.8800° N     121.7269° W    46.880000   -121.726900
43  48.7718° N     121.2985° W    48.771800   -121.298500
44  47.8021° N     123.6044° W    47.802100   -123.604400
45  34.9583° N     109.7594° W    34.958300   -109.759400
46  36.4906° N     121.1825° W    36.490600   -121.182500
47  41.4017° N     124.0417° W    41.401700   -124.041700
48  40.3428° N     105.6836° W    40.342800   -105.683600
49  32.1831° N     110.6127° W    32.183100   -110.612700
50  36.4864° N     118.5658° W    36.486400   -118.565800
51  38.4755° N      78.4535° W    38.475500    -78.453500
52  46.9790° N     103.5387° W    46.979000   -103.538700
53  18.3435° N      64.7501° W    18.343500    -64.750100
54  48.4711° N      92.8458° W    48.471100    -92.845800
55  43.5724° N     103.4416° W    43.572400   -103.441600
56  60.9234° N     142.7339° W    60.923400   -142.733900
57  44.4280° N     110.5885° W    44.428000   -110.588500
58  37.8651° N     119.5383° W    37.865100   -119.538300
59  37.2982° N     113.0263° W    37.298200   -113.026300

In [70]:
# Drop the 'lat' and 'long' columns
df.drop(['lat', 'long'], axis=1, inplace=True)
df.rename(columns={'lat_decimal': 'lat'}, inplace=True)
df.rename(columns={'long_decimal': 'lng'}, inplace=True)
# Display the DataFrame with decimal degrees and the 'lat' column renamed
print(df)

                                          name                      location  \
0                         Acadia National Park                         Maine
1                 American Samoa National Park      American Samoa Territory
2                         Arches National Park                          Utah
3                       Badlands National Park                  South Dakota
4                       Big Bend National Park                         Texas
5                       Biscayne National Park                       Florida
6   Black Canyon of the Gunnison National Park                      Colorado
7                   Bryce Canyon National Park                          Utah
8                    Canyonlands National Park                          Utah
9                   Capitol Reef National Park                          Utah
10              Carlsbad Caverns National Park                    New Mexico
11                      Congaree National Park                South Carolina
12                   Crater Lake National Park                        Oregon
13               Cuyahoga Valley National Park                          Ohio
14                  Death Valley National Park         California and Nevada
15                        Denali National Park                        Alaska
16                  Dry Tortugas National Park                       Florida
17                    Everglades National Park                       Florida
18           Gates of the Arctic National Park                        Alaska
19                  Gateway Arch National Park                      Missouri
20                       Glacier National Park                       Montana
21                   Glacier Bay National Park                        Alaska
22                  Grand Canyon National Park                       Arizona
23                   Grand Teton National Park                       Wyoming
24                   Great Basin National Park                        Nevada
25              Great Sand Dunes National Park                      Colorado
26         Great Smoky Mountains National Park  North Carolina and Tennessee
27           Guadalupe Mountains National Park                         Texas
28                     Haleakala National Park                        Hawaii
29              Hawaii Volcanoes National Park                        Hawaii
30                   Hot Springs National Park                      Arkansas
31                 Indiana Dunes National Park                       Indiana
32                   Isle Royale National Park                      Michigan
33                   Joshua Tree National Park                    California
34                        Katmai National Park                        Alaska
35                  Kenai Fjords National Park                        Alaska
36                  Kings Canyon National Park                    California
37                  Kobuk Valley National Park                        Alaska
38                    Lake Clark National Park                        Alaska
39                        Lassen Volcanic Park                    California
40                           Mammoth Cave Park                      Kentucky
41                    Mesa Verde National Park                      Colorado
42                 Mount Rainier National Park                    Washington
43                North Cascades National Park                    Washington
44                       Olympic National Park                    Washington
45              Petrified Forest National Park                       Arizona
46                     Pinnacles National Park                    California
47                       Redwood National Park                    California
48                Rocky Mountain National Park                      Colorado
49                       Saguaro National Park                       Arizona
50                       Sequoia National Park                    California
51                    Shenandoah National Park                      Virginia
52            Theodore Roosevelt National Park                  North Dakota
53                Virgin Islands National Park           U.S. Virgin Islands
54                     Voyageurs National Park                     Minnesota
55                     Wind Cave National Park                  South Dakota
56            Wrangell-St. Elias National Park                        Alaska
57                   Yellowstone National Park                       Wyoming
58                      Yosemite National Park                    California
59                          Zion National Park                          Utah

          lat         lng
0   44.350000  -68.216667
1  -14.000000 -170.000000
2   38.000000 -109.000000
3   43.750000 -102.500000
4   29.000000 -103.000000
5   25.000000  -80.000000
6   38.000000 -107.000000
7   37.583333 -112.183333
8   38.000000 -109.000000
9   38.200000 -111.166667
10  32.000000 -104.000000
11  33.791900  -80.749000
12  42.000000 -122.000000
13  41.280800  -81.567800
14  36.505400 -117.079400
15  63.282800 -150.789400
16  24.628500  -82.873200
17  25.286600  -80.898700
18  67.783333 -153.300000
19  38.624900  -90.185900
20  48.759600 -113.787000
21  58.665800 -136.900200
22  36.267900 -112.353500
23  43.790400 -110.681800
24  38.930000 -114.263400
25  37.765800 -105.623600
26  35.613100  -83.553200
27  31.923300 -104.866300
28  20.720400 -156.155200
29  19.496400 -155.466200
30  34.526900  -93.069100
31  41.653300  -87.052400
32  47.995900  -88.909300
33  33.873400 -115.901000
34  58.586200 -154.969800
35  59.848700 -150.187900
36  36.887900 -118.555100
37  67.357500 -159.213700
38  60.624200 -153.305800
39  40.497700 -121.420700
40  37.181500  -86.150500
41  37.230900 -108.461800
42  46.880000 -121.726900
43  48.771800 -121.298500
44  47.802100 -123.604400
45  34.958300 -109.759400
46  36.490600 -121.182500
47  41.401700 -124.041700
48  40.342800 -105.683600
49  32.183100 -110.612700
50  36.486400 -118.565800
51  38.475500  -78.453500
52  46.979000 -103.538700
53  18.343500  -64.750100
54  48.471100  -92.845800
55  43.572400 -103.441600
56  60.923400 -142.733900
57  44.428000 -110.588500
58  37.865100 -119.538300
59  37.298200 -113.026300

In [73]:
df.to_csv("Archive/national_PARKS.csv", index=False)